spring.application.name=backend-java

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/demoerp
spring.datasource.username=${DB_USER:demoerp}
spring.datasource.password=${DB_PASS:demoerp}
spring.jpa.hibernate.ddl-auto=none
